version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: insight-pulse-container
    ports:
      - "8080:8080"
    networks:
      - my-network
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USER=seniorTheo
      - DB_PASSWORD=userPassword89
    

  mariadb:
    image: mariadb:latest
    container_name: my-go-mariadb-container
    environment:
      MYSQL_ROOT_PASSWORD: 'testDb17root'
      MYSQL_USER: 'seniorTheo'
      MYSQL_PASSWORD: 'userPassword89'  
      MYSQL_DATABASE: 'f_insights'
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge 

volumes:
  mysqldata: {}